language: node_js

node_js:
- '4.1.1'

before_install:
- wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
- tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
- sudo rm -rf /usr/local/phantomjs/bin/phantomjs
- sudo mv phantomjs /usr/local/phantomjs/bin/phantomjs
- npm install --quiet -g gulp jspm typescript tsd
- jspm config registries.github.remote https://github.jspm.io
- jspm config registries.github.auth YjA5MTprcnRnbWszYQ==
- jspm config registries.github.maxRepoSize 0
- jspm config registries.github.handler jspm-github

#before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
- sleep 3

script:
- gulp compile
- gulp test:unit

cache:
  directories:
  - ./node_modules
  - ./vendor
  - $HOME/.nvm

sudo: false
